### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq.models'

### ISSUE THREAD

**Issue by jiaohuix** [vhch/PiNMT#1]
Dear author
I have been studying your paper on incorporating pre-trained language models into neural machine translation, and find it truly insightful. Your code implementation is very helpful for my research.

I notice that the models module referenced in the paper is currently not open-sourced in the repository. As this module is key to re-implementing the methods, I sincerely request you to open-source it when possible. This will greatly benefit researchers like me to better understand and extend your excellent work.

Please let me know if you have any concerns regarding open-sourcing this module. I highly look forward to your kind consideration, and will appreciate your efforts on this!

Best regards

**Comment by vhch** [comment]
Thank you for your interest in our paper and for pointing out the absence of the models module. Your observation was instrumental in us adding it to our repository. Please feel free to reach out for any further queries.

Best regards

**Comment by jiaohuix** [comment]
Wow, you have released models module so quickly! This will undoubtedly aid me in further studying and understanding your ideal. If I have any other questions, I will not hesitate to contact you. Thanks~~~~
